insert into publisher (name, address, email, phone_no, bank_acc) values ('George Allen & Unwin', '878 Ilene Terrace', 'whubble0@auda.org.au', '4682072868', 0);
insert into publisher (name, address, email, phone_no, bank_acc) values ('Bloomsbury', '5 Westport Hill', 'kcarletti1@edublogs.org', '1014187086', 0);
insert into publisher (name, address, email, phone_no, bank_acc) values ('Reynal & Hitchcock', '162 Summer Ridge Hill', 'blibbis2@salon.com', '2956180696', 0);
insert into publisher (name, address, email, phone_no, bank_acc) values ('Collins Crime Club', '0668 Truax Parkway', 'kograda3@zdnet.com', '5171972967', 0);
insert into publisher (name, address, email, phone_no, bank_acc) values ('Geoffrey Bles', '901 Transport Way', 'mfernihough4@hc360.com', '8618163175', 0);
insert into publisher (name, address, email, phone_no, bank_acc) values ('Longmans', '8326 Summer Ridge Junction', 'mmacgown5@latimes.com', '1136967343', 0);
insert into publisher (name, address, email, phone_no, bank_acc) values ('Doubleday', '5 Blaine Street', 'lhallett6@blogspot.com', '3762393857', 0);
insert into publisher (name, address, email, phone_no, bank_acc) values ('Little, Brown and Company', '09 Westport Terrace', 'gbrampton7@sfgate.com', '1918610850', 0);
insert into publisher (name, address, email, phone_no, bank_acc) values ('Warner Books', '64763 Shoshone Way', 'messlement8@freewebs.com', '2275994141', 0);
insert into publisher (name, address, email, phone_no, bank_acc) values ('Olympia Press', '7 Larry Parkway', 'ganfosso9@bloglovin.com', '7324831540', 0);
insert into publisher (name, address, email, phone_no, bank_acc) values ('J. B. Lippincott & Co.', '820 Warrior Hill', 'tmacfadyena@java.com', '8326155079', 0);
insert into publisher (name, address, email, phone_no, bank_acc) values ('Random House', '970 Mesta Park', 'ntriggsb@webmd.com', '3063906772', 0);
insert into publisher (name, address, email, phone_no, bank_acc) values ('Aschehoug', '96453 Stang Alley', 'tklugmanc@ted.com', '5723381369', 0);
insert into publisher (name, address, email, phone_no, bank_acc) values ('Chilton Books', '697 Green Trail', 'speasbyd@stanford.edu', '2445971137', 0);
insert into publisher (name, address, email, phone_no, bank_acc) values ('Viking Press', '563 Park Meadow Place', 'ebowllere@wired.com', '2679720142', 0);
insert into publisher (name, address, email, phone_no, bank_acc) values ('Voyager Books', '872 Roth Circle', 'rtummasuttif@gmpg.org', '7398725733', 0);
insert into publisher (name, address, email, phone_no, bank_acc) values ('Charles Scribner''s Sons', '338 Esch Avenue', 'dfindersg@msn.com', '3384238701', 0);
insert into publisher (name, address, email, phone_no, bank_acc) values ('Riverhead Books', '2 Northland Parkway', 'vivainh@loc.gov', '4782225505', 0);
insert into publisher (name, address, email, phone_no, bank_acc) values ('SuperNowa', '8154 Mallory Terrace', 'tscholefieldi@wiley.com', '2339227682', 0);
insert into publisher (name, address, email, phone_no, bank_acc) values ('Knopf Canada', '71127 Michigan Terrace', 'tgrzegorzewskij@howstuffworks.com', '7653485579', 0);
